Run xstatic version checker in project repo
The xstatic version checker script expects to be able to ls contents
relative to the root of the project repo otherwise it fails with:

  Traceback (most recent call last):
    File "xstatic_check_version.py", line 26, in <module>
      for name in os.listdir('xstatic/pkg'):
  OSError: [Errno 2] No such file or directory: 'xstatic/pkg'

Fix this by running the script after chdir'ing into the repo.

Change-Id: Ifd8f3db93b8c600b361ec894a404c54255b888de