Revert "Re-add translation support to build-openstack-releasenotes"
This reverts commit d2e10dfe578f0c7c3468a35435129d85635dfa6b.

This was breaking build-openstack-releasenotes builds with:

    FileNotFoundError: [Errno 2] No such file or directory: 'tox'

Change-Id: Ic6aafb92d457115a5c6f90eba078fac66cb75ca1
Signed-off-by: Pierre Riteau <pierre@stackhpc.com>